# ABOUTME: golangci-lint v2 configuration for digest project
# ABOUTME: Enables linters for bugs, performance, security, style, and maintainability

version: "2"
run:
  tests: true
linters:
  enable:
    - bodyclose
    - contextcheck
    - copyloopvar
    - errchkjson
    - gocritic
    - gocyclo
    - misspell
    - nilerr
    - nilnil
    - prealloc
    - unconvert
    - unparam
    - wastedassign
    - whitespace
  disable:
    - errcheck
    - errorlint
    - exhaustive
    - exhaustruct
    - funlen
    - gocognit
    - goconst
    - gosec
    - makezero
    - nestif
    - paralleltest
    - tagliatelle
    - testpackage
    - thelper
    - varnamelen
    - wrapcheck
  settings:
    gocyclo:
      min-complexity: 20
    govet:
      disable:
        - shadow
        - fieldalignment
      enable-all: true
    misspell:
      locale: US
    staticcheck:
      checks:
        - all
        - -ST1000  # Package comments not required (we use ABOUTME comments)
  exclusions:
    generated: lax
    rules:
      - linters:
          - gocritic
          - gocyclo
        path: _test\.go
    paths:
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
formatters:
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
